### ISSUE TITLE
netlify CMS stylesheeet - images

### ISSUE THREAD

**Issue by dannystaple** [orionrobots/orionrobots.github.io#18]
images on the blog are resized (through CSS) to fit the page width. 
Images in netlify aren't. This may just be a css override I can make in the netlify admin index page.

**Comment by dannystaple** [comment]
I did an inspect, and tried:
```css
 .frame-content img {
      display: inline-block;
      height: auto;
      max-width: 100%;
    }

    .frame-content {
      font-family: "Roboto","Helvetica Neue",Helvetica,Arial,sans-serif;
      font-size: 14px;
    }
```
However, I failed to spot that the preview is an iframe. Not sure how to attribute CSS to that yet.
